# The Basics

- ndarray.ndim  
the number of axes (dimensions) of the array. In the Python world, the
number of dimensions is referred to as rank.
- ndarray.shape  
the dimensions of the array. This is a tuple of integers indicating the size of
the array in each dimension. For a matrix with n rows and m columns,
shape will be (n,m). The length of the shape tuple is therefore the rank,
or number of dimensions, ndim.
- ndarray.size  
the total number of elements of the array. This is equal to the product of
the elements of shape.
-  ndarray.dtype  
an object describing the type of the elements in the array. One can create
or specify dtype’s using standard Python types. Additionally NumPy
provides types of its own. numpy.int32, numpy.int16, and numpy.float64
are some examples.
- ndarray.itemsize  
the size in bytes of each element of the array. For example, an array of
elements of type float64 has itemsize 8 (=64/8), while one of type
complex32 has itemsize 4 (=32/8). It is equivalent to
ndarray.dtype.itemsize.
- ndarray.data  
the buffer containing the actual elements of the array. Normally, we won’t
need to use this attribute because we will access the elements in an array
using indexing facilities.

In [2]:
import numpy as np

values = np.array([3.4, 44, 42, 998.888])

print(values.ndim)
print(values.shape)
print(values.size)
print(values.dtype)
print(values.itemsize)
print(values.data)

1
(4,)
4
float64
8


In [3]:
a = np.arange(15).reshape(3, 5)
print(a)

print(a.shape)

print(a.ndim)

print(a.dtype.name)

print(a.itemsize)

print(a.size)

print(type(a))

b = np.array([6, 7, 8])
print(b)

print(type(b))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
2
int32
4
15
<class 'numpy.ndarray'>
[6 7 8]
<class 'numpy.ndarray'>


# Array Creation

In [4]:
import numpy as np

a = np.array([2,3,4])
print(a)
print(a.dtype)
b = np.array([1.2, 3.5, 5.1])
print(b.dtype)

[2 3 4]
int32
float64


In [5]:
b = np.array([(1.5,2,3), (4,5,6)])
print(b)
c = np.array( [ [1,2], [3,4] ], dtype=complex )
print(c)
print(np.zeros( (3,4) ))
print(np.ones( (2,3,4), dtype=np.int16 )) # dtype can also be specified
print(np.empty( (2,3) )) # uninitialized, output may vary

[[1.5 2.  3. ]
 [4.  5.  6. ]]
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[1.39069238e-309 1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309 1.39069238e-309]]


In [6]:
print(np.arange( 10, 30, 5 ))
print(np.arange( 0, 2, 0.3 ))

[10 15 20 25]
[0.  0.3 0.6 0.9 1.2 1.5 1.8]


In [7]:
from numpy import pi

print(np.linspace( 0, 2, 9 )) # 9 numbers from 0 to 2
x = np.linspace( 0, 2*pi, 100 ) # useful to evaluate function at lots of points
print(x)
f = np.sin(x)
print(f)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
[0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4.88692191
 4.95038842 5.01385494 5.07732146 5.14078798 5.2042545  5.26772102
 5.33118753 5.394

# Printing Arrays

In [21]:
a = np.arange(6) # 1d array
print(a)

b = np.arange(12).reshape(4,3) # 2d array
print(b)

c = np.arange(24).reshape(2,3,4) # 3d array
print(c)

[0 1 2 3 4 5]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [19]:
print(np.arange(10000))

print(np.arange(10000).reshape(100,100))

[   0    1    2 ... 9997 9998 9999]
[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [20]:
import sys

np.set_printoptions(threshold=sys.maxsize)

In [18]:
np.set_printoptions(threshold=1000) # default value

# Basic Operations

In [22]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
print(b)

c = a-b
print(c)

print(b**2)

print(10*np.sin(a))

[0 1 2 3]
[20 29 38 47]
[0 1 4 9]
[ 9.12945251 -9.88031624  7.4511316  -2.62374854]


In [25]:
A = np.array( [[1,1], [0,1]] )

B = np.array( [[2,0], [3,4]] )

print(A*B)

print(A.dot(B))

print(np.dot(A, B))


[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


In [28]:
a = np.ones((2,3), dtype=int)
b = np.random.random((2,3))
a *= 3
print(a)

b += a
print(b)

a += b # b is not automatically converted to integer type

[[3 3 3]
 [3 3 3]]
[[3.55237924 3.92479842 3.53558315]
 [3.44366521 3.84945461 3.62275542]]


UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

In [30]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0,pi,3)
print(b.dtype.name)

c = a+b
print(c)
print(c.dtype.name)

d = np.exp(c*1j)
print(d)
print(d.dtype.name)

float64
[1.         2.57079633 4.14159265]
float64
[ 0.54030231+0.84147098j -0.84147098+0.54030231j -0.54030231-0.84147098j]
complex128


In [31]:
a = np.random.random((2,3))
print(a)
print(a.sum())
print(a.min())
print(a.max())

[[0.86396259 0.62740598 0.67816375]
 [0.19440378 0.46597201 0.90510605]]
3.735014159920406
0.19440378414692006
0.905106045363323


In [32]:
b = np.arange(12).reshape(3,4)
print(b)

print(b.sum(axis=0)) # sum of each column
print(b.min(axis=1)) # min of each row

print(b.cumsum(axis=1)) # cumulative sum along each row

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]
[0 4 8]
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]
