# The Basics

- ndarray.ndim  
the number of axes (dimensions) of the array. In the Python world, the
number of dimensions is referred to as rank.
- ndarray.shape  
the dimensions of the array. This is a tuple of integers indicating the size of
the array in each dimension. For a matrix with n rows and m columns,
shape will be (n,m). The length of the shape tuple is therefore the rank,
or number of dimensions, ndim.
- ndarray.size  
the total number of elements of the array. This is equal to the product of
the elements of shape.
-  ndarray.dtype  
an object describing the type of the elements in the array. One can create
or specify dtype’s using standard Python types. Additionally NumPy
provides types of its own. numpy.int32, numpy.int16, and numpy.float64
are some examples.
- ndarray.itemsize  
the size in bytes of each element of the array. For example, an array of
elements of type float64 has itemsize 8 (=64/8), while one of type
complex32 has itemsize 4 (=32/8). It is equivalent to
ndarray.dtype.itemsize.
- ndarray.data  
the buffer containing the actual elements of the array. Normally, we won’t
need to use this attribute because we will access the elements in an array
using indexing facilities.

In [1]:
import numpy as np

values = np.array([3.4, 44, 42, 998.888])

print(values.ndim)
print(values.shape)
print(values.size)
print(values.dtype)
print(values.itemsize)
print(values.data)

1
(4,)
4
float64
8


In [2]:
a = np.arange(15).reshape(3, 5)
print(a)

print(a.shape)

print(a.ndim)

print(a.dtype.name)

print(a.itemsize)

print(a.size)

print(type(a))

b = np.array([6, 7, 8])
print(b)

print(type(b))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
2
int32
4
15
<class 'numpy.ndarray'>
[6 7 8]
<class 'numpy.ndarray'>
